services:
  https:
    container_name: https_server
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/www:/code
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/ssl