services:

  postgres:
      image: postgres
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password

  keycloak:
      image: quay.io/keycloak/keycloak:15.0.2
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        PROXY_ADDRESS_FORWARDING: "true"
      ports:
        - 8081:8080
      depends_on:
        - postgres

  web:
      container_name: web_server
      image: nginx:latest
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./nginx/www:/code
        - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/ssl:/ssl
      depends_on:
        - keycloak