networks:
  api-network:
    name: api-network
  auth-network:
    name: auth-network


services:
  web:
    container_name: web_server
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/www:/code
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/ssl
    networks:
     - api-network


  api:
    build:
      context: api
    container_name: backend_api
    environment:
      PORT: 1200
    ports:
      - 1200:1200
    volumes:
      - ./api/src:/app
    restart: always
    networks:
      api-network:
        aliases:
          - backend-api
      auth-network:
        aliases:
          - backend-api


  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    networks:
      auth-network:
        aliases:
          - dbAddress


  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    restart: always
    command: start-dev
    ports:
        - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: mariadb
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_ADDR: dbAddress
      DB_DATABASE: keycloak
      PROXY_ADDRESS_FORWARDING: "true"
      KC_HTTP_RELATIVE_PATH: "/keycloak"
      KC_PROXY: edge
    networks:
      auth-network:
        aliases:
          - keycloakAddress